Repository GDSC-BSIOTR/Books-Info, pull requests merged in 2022-10, with the labels that each got.

#72 Update books.json
  books.json
Labels: hacktoberfest-accepted

#71 Update books.json
  books.json
Labels: hacktoberfest-accepted

#74 Update books.json
  books.json
Labels: hacktoberfest-accepted

#73 added reminders of him
  books.json
Labels: hacktoberfest-accepted

#75 Added book
  books.json
Labels: hacktober-accepted

#76 2states Book added
  books.json
Labels: hacktober-accepted

#77 book added
  books.json
Labels: hacktober-accepted

#79 khalid hussain book added
  books.json
Labels: hacktober-accepted

#80 Added Book of The Almanack of Naval Ravikant
  books.json
Labels: hacktober-accepted

#81 book added
  books.json
Labels: hacktober-accepted

#83 removed all errors and added the book The Theory of Everything
  books.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#84 New Book Added
  books.json
Labels: hacktoberfest, hacktoberfest-accepted

#86 Added "Never split the difference"
  books.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#87 Add a new book
  books.json
Labels: hacktober-accepted

#88 Add a new book
  books.json
Labels: hacktober-accepted

#89 Remove All errors and added a book Atomic Habits
  books.json
Labels: hacktoberfest, hacktoberfest-accepted

#90 Added id 2304
  books.json
Labels: hacktoberfest, hacktoberfest-accepted

#91 Updated JSON file
  books.json
Labels: hacktober-accepted

#93 I have added book Laws of Power
  books.json
Labels: hacktober-accepted

#94 Added a Book
  books.json
Labels: hacktober-accepted

#96 Added TheAlchemist
  books.json
Labels: hacktoberfest-accepted, hacktober-accepted

#97 Added the canterville
  books.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#98 I was add 2 book
  books.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#99 Added book Eat That Frog
  books.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#102 Added a book related to children .
  books.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#105 Update books.json
  books.json
Labels: hacktoberfest-accepted, hacktober-accepted

#107 Update books.json
  books.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#109 Update books.json
  books.json
Labels: hacktoberfest-accepted, hacktober-accepted

#110 Update books.json
  books.json
Labels: hacktoberfest-accepted

#111 Updated books.json and fixed errors
  books.json
Labels: hacktoberfest-accepted

#112 Adding Book:"How To Win Friends&Influence People"
  books.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#113 added Introduction to Algorithms
  books.json
Labels: hacktoberfest-accepted, hacktober-accepted

#116 added
  books.json
Labels: hacktoberfest-accepted

#117 Added
  books.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#115 update
  books.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#118 Update books.json
  books.json
Labels: hacktoberfest-accepted, hacktober-accepted

#119 Update books.json
  books.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#120 fixed syntax and added a book
  books.json
Labels: hacktoberfest-accepted, hacktober-accepted

#121 Updated books.json
  books.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#122 Added New Book
  books.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#123 Update books.json
  books.json
Labels: hacktoberfest-accepted, hacktober-accepted

#124 Update books.json
  books.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#125 Update books.json
  books.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#126 Added Book by Leo Tolstoy
  books.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#127 Update books.json
  books.json
Labels: hacktoberfest-accepted, hacktober-accepted

#128 Update books.json
  books.json
Labels: hacktoberfest-accepted, hacktober-accepted

#129 added book two states
  books.json
Labels: hacktoberfest-accepted, hacktober-accepted

#130 Update books.json
  books.json
Labels: hacktoberfest-accepted, hacktober-accepted

#131 Update books.json
  books.json
Labels: hacktoberfest-accepted, hacktober-accepted

#132 changes done
  books.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#133 Update books.json
  books.json
Labels: hacktoberfest-accepted, hacktober-accepted

#135 a mid summer night's dream book
  books.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#136 Update books.json
  books.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#139 Added New Book
  books.json
Labels: hacktoberfest-accepted, hacktober-accepted

#140 Added book
  books.json
Labels: hacktoberfest-accepted, hacktober-accepted

#143 harrypotter
  books.json
Labels: hacktoberfest-accepted, hacktober-accepted

#144 add new book and fix errors in json
  books.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#145 Update books.json
  books.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#147 Update books.json
  books.json
Labels: hacktoberfest-accepted, hacktober-accepted

#148 add girl on the cliff book
  books.json
Labels: hacktoberfest-accepted, hacktober-accepted

#149 Update Books.json
  books.json
Labels: hacktoberfest-accepted, hacktober-accepted

#150 Update books.json
  books.json
Labels: hacktoberfest-accepted, hacktober-accepted

#151 Update books.json
  books.json
Labels: hacktoberfest-accepted, hacktober-accepted

#152 Update books.json
  books.json
Labels: hacktoberfest-accepted, hacktober-accepted

#153 Update books.json
  books.json
Labels: hacktoberfest-accepted, hacktober-accepted

#156 Update books.json
  books.json
Labels: hacktoberfest-accepted, hacktober-accepted

#157 added new book info
  books.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#160 Update books.json
  books.json
Labels: hacktoberfest-accepted

#159 Update books.json
  books.json
Labels: hacktoberfest-accepted

#158 Update books.json
  books.json
Labels: hacktoberfest-accepted
