Repository GDSC-BSIOTR/Books-Info, pull requests merged in 2022-09, with the labels that each got.

#5 Update books.json
  books.json
Labels: hacktoberfest, hacktoberfest-accepted

#46 updated
  books.json
Labels: hacktoberfest-accepted

#36 Added book info
  books.json
Labels: hacktoberfest-accepted

#47 Update books.json
  books.json
Labels: hacktoberfest-accepted

#21 new name
  books.json
Labels: hacktoberfest-accepted

#51 Added id 41
  books.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#53 updated
  books.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#55 Update books.json
  books.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#57 Update books.json
  books.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#56 added book at 101
  books.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#58 Update books.json
  books.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#59 committed!
  books.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#60 Book
  books.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#61 Added line 125
  books.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#62 Update books.json
  books.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#63 Update books.json
  books.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#65 Book name added
  books.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#66 added book id
  books.json
Labels: hacktoberfest-accepted, hacktober-accepted

#67 Update books.json
  books.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#69 Update books.json
  books.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#68 Update books.json
  books.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#70 new
  books.json
Labels: hacktoberfest, hacktober-accepted
